# Introduction

The replacement of the Gravettian culture by the Solutrean, impacted by the adverse climatic conditions onset by the Heinrich Event 2 and its development through the last glacial maximum, continues to be an essential topic for understanding the Upper Paleolithic and Human adaptations. The Proto-Solutrean is, in this topic, an essential piece to understand how hunter-gatherer communities adapted, reinvented and destroyed behaviours that eventually allowed the development of the Solutrean. However, the existing knowledge on this technocomplex is still geographically constricted and lacking good chronological markers (Cascalheira and Bicho 2013), which hampers the understanding of the Proto-Solutrean itself and its role in the transition between the Gravettian and Solutrean technocomplexes.

By understanding the need of a better understanding of the Proto-Solutrean and how adverse climate impacted these communities, this thesis aims to answer the following question: what impact did the Heinrich 2 event have on the technological organization of human communities, on the onset of the last glacial maximum, in south western Iberia?

To answer this question, the present thesis has a number of goals, each connected to a problematic regarding the topic at hand, which will be met with resource to the lithic proto-solutrean assemblages of two sites, Vale Boi (south of Portugal) and Lapa do Picareiro (central Portugal).

To understand technological organization, our goal is to characterize and understand technological patterns, reduction sequences and assemblage variability in Proto-Solutrean occupations for both sites, as well as comprehend raw material use and preference patterns. The results will then be compared with the existing data from other Proto-Solutrean assemblages, mostly from the Estremadura Portuguesa area.

To better comprehend the transition from the Gravettian into the Solutrean, and how climate might have impacted this transition, we aim to test the existing Proto-Solutrean transitional models, the Two-phase and Three-phase, and understand how the two studied sites fit within the models, and whether there exists geographic variability. To do so, two question need to be answered: 1) if the proto-solutrean layers in Vale Boi show a Terminal Gravettian horizon; 2) if the two identified proto-solutrean phases in Lapa do Picareiro (Terminal Gravettian and Proto-Solutrean) show chronological significance.

Through the accomplishment of these goals, we hope to contribute to the understanding of the Proto-Solutrean in western Iberia, but also to the topic of the Gravettian culture replacement and subsequentially, the appearance of the Solutrean, through new data resulting from recent excavations and a wider geographic range (extending the knowledge of this transition to the south of Portugal).

The present thesis is organized in 9 chapters. Chapter 2, which follows the present introduction, will offer some contextualization on the human adaptations which characterize the start of the last glacial maximum, starting with a brief review of paleoclimate during the Upper Paleolithic in western Iberia, the several climate events and their relationship with cultural systems, and finishing with a brief overview of the Proto-Solutrean, its origins, chronology, technological characteristics and evolution models.

On chapter 3 we will introduce the archaeological site of Vale Boi, with a brief description of its localization and geological context, followed by an overview of excavation works, excavation methodology, human occupation layers through the several areas, and stratigraphy of the Terrace area, with particular focus on layer 4E and 5, the Proto-Solutrean occupation layers.

Chapter 4 follows the same organization as the previous chapter, this time focusing on the introduction of the archaeological site of Lapa do Picareiro, on the final part describing instead layers U and T which correspond to the Terminal Gravettian and Proto-Solutrean occupations.

Chapter 5 is dedicated to the description of the methodology employed in both the lithic assemblage analysis and data analysis.

Chapter 6 and 7 will follow the same structure, to present the results obtained in the analysis of the assemblage from Vale Boi and Lapa do Picareiro respectively. As such, the chapters are divided between assemblage description, raw materials and technology, this latter subsection presenting results from the descriptive and multivariate analysis.

Chapter 8 will consist on the discussion of both the results shown in the previous chapters, whenever possible connecting and comparing them, and extending this comparison to other results from Proto-Solutrean assemblages, mostly from the Portuguese Estremadura.

Chapter 9 offers some conclusions, systematizing the analysis interpretations and discussion.