# Conclusion

Phases U/Lower T and Middle T from Lapa do Picareiro and Levels 5 and 4E from Vale Boi have allowed the expansion of our understading on the Terminal Gravettian and Proto-Solutrean cultural horizons, not only testing the existing evolutionary models, as well as extending the geographical range of these technocomplexes in Portugal. 

As such, through the data obtained from these two sites, both recently excavated, with resource to the most advanced field methods, and for which a contextualized set of radiocarbon dates are available, the present study has reached 4 main conclusions, each responding to the goals defined in Chapter 1:

*	Technological patterns are similar in the analysed assemblages, dominated by reduction sequences focused on the obtention of elongated blanks (mostly bladelets for Lower 5 and U/Lower T) and flakes, though prismatic cores, with little platform preparation and with resource to unidirectional strategies. These strategies are equally applied to chert and quartz.

*	Differences between phases within each site are mostly explained by differences in raw material use and presence of Vale Comprido technology. In a first phase, quartz is used in high frequencies mainly for the production of bladelets and flakes, reducing in frequency in posterior moments. Vale Comprido technology seems to be an innovation in the second moment.

*	This first phase (U/Lower T and Lower 5), corresponding to a Terminal Gravettian occupation, seems to occur around 27-26 ka cal BP (at Lapa do Picareiro and Vale Boi, respectively). The second phase (Upper 5/4E and Middle T) occurs around 25.5 ka cal BP, corresponding to the Proto-Solutrean,  undoubtedly in the case of Vale Boi and with some reservations in the case of Lapa do Picareiro (see Chapter 6 and below). The technological and raw material patterns correlated with the absolute chronology and separation of the stratigraphic contexts show that the Three-phase model seems to apply best to sites in the Estremadura and the south of Portugal. Consequently, the Terminal Gravettian is likely not a functional facies of the Proto-Solutrean, but an independent cultural horizon (as already suggested by Almeida 2000).

*	Middle T from Lapa do Picareiro shows a horizon with technological similarities with the Proto-Solutrean, but without a typical Vale Comprido technology, having instead similar blanks with some resemblances to Middle Solutrean blanks and points. Radiocarbon dates place this occupation extending to more recent chronologies than other sites, while keeping some chronological overlap with Proto-Solutrean occupations in the Estremadura and southern Portugal. This pattern, in turn, offers two alternative hypothesis: 1) it represents a Proto-Solutrean occupation, happening until younger dates than other sites, but without typical Vale Comprido technology due to functional specifities of the site; 2) it corresponds to an Early Solutrean occupation of transitional characteristics with similarities to Proto-Solutrean and Middle Solutrean tools, a horizon so far not identified in Portugal.

\  

The latter is still rather inconclusive, needing further studies to understand the particularities of this industry at Lapa do Picareiro and its representation in other sites of the Portuguese Estremadura. This may be achieved through the analysis of, not only Vale Comprido technology using a more complete set of morpho-metrical data (avoiding as much as possible subjective typological attributions), but also through the analysis of blade reduction schemes for the sites dated to the transition, as well as Middle Solutrean blanks and *pointes à face plan* production.

Assessing these patterns is important to understand a link that seems to be missing in the Upper Paleolithic in Portugal and that connects the Proto-Solutrean to the Solutrean, further building onto the existing models for the Gravettian-Solutrean transition. Still, it should be kept in mind that the lack of chronological resolution from most of the currently available radiocarbon dates, as well as the contextual problems of most of the sites attributed to the transition, hampers the identification of small chronological differences and of rapid cultural changes in the archaeological record.

Furthermore, in the future, it seems important to understand the presence of dolerite in Vale Boi. Given the now known internal characteristics of this raw material, it may be interesting to test its actual nonexistence in the other occupations in the site, to further understand possible niche expansions in this horizon, as a result to climatic changes.
